public class NestedTryDemo {
    public static void main(String[] args) {
        try {
            System.out.println("Outer try block starts.");

            
            try {
                int a = 10;
                int b = 0;
                System.out.println("Inner try block level 1.");
                int result = a / b; // This will cause ArithmeticException
                System.out.println("Result: " + result);
            } catch (ArithmeticException e1) {
                System.out.println("Caught ArithmeticException: " + e1.getMessage());
            }

        
            try {
                System.out.println("Inner try block level 2.");
                String str = null;
                System.out.println("Length of string: " + str.length()); // This will cause NullPointerException
            } catch (NullPointerException e2) {
                System.out.println("Caught NullPointerException: " + e2.getMessage());
            }

            System.out.println("Outer try block ends normally.");

        } catch (Exception e) {
            System.out.println("Caught in outer catch block: " + e.getMessage());
        }

        System.out.println("Program continues after nested try blocks.");
    }
}
